### ISSUE TITLE
"Execute" runs the script in AHK v1 by default

### ISSUE THREAD

**Issue by gczark** [samfisherirl/Auto-GUI-for-AHK-v2#1]
I have both v1 and v2 installed. Error message tells that cannot call Gui().
Please add `#Require` at the beginning of the script by default.

![image](https://user-images.githubusercontent.com/28706158/236229052-06be50af-c75e-4d01-b4fc-d776a081e52c.png)

**Comment by samfisherirl** [comment]
> I have both v1 and v2 installed. Error message tells that cannot call Gui(). Please add `#Require` at the beginning of the script by default.
> 
> ![image](https://user-images.githubusercontent.com/28706158/236229052-06be50af-c75e-4d01-b4fc-d776a081e52c.png)

good call, fixing now.
